version: "3.4"

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /var/docker/sonarr:/config
      - /var/docker/sonarr/tv:/tv #optional
      - /var/docker/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /var/docker/radarr:/config
      - /var/docker/radarr/tv:/movies #optional
      - /var/docker/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - AUTO_UPDATE=true #optional
    volumes:
      - /var/docker/jackett:/config
      - /var/docker/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /var/docker/nginx/template:/etc/nginx/templates
      - /var/docker/nginx/conf:/etc/nginx/conf.d
      - /var/docker/nginx/html/:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
